### ISSUE TITLE
unnötigstes Issue #1

### ISSUE THREAD

**Issue by Sprudeel** [ninoflorj/schuetziwoche-wp-plugin#1]
In schuetziwoche-wp-plugin/schuetziwoche/admin.php befindet sich auf den Linien 37 - 39 folgender Code:

```php
 <tr valign="top"><th scope="row">Kosten (Znacht & Übernachtung):</th>
     <td><input type="text" name="'. SCHUETZIWOCHE_OPTIONS.'[cost_eat]" value="'. $options['cost_eat'] .'" /> Fr.</td>
 </tr>
```

In den Einstellungen wird die Variabel `cost_eat` als Kosten von Znacht und Übernachtung definiert, jedoch wird sie in ziemlich allen anderen Instanzen als die Kosten für nur den Znacht verwendet. Dies kann zu Verwirrung führen, bitte fixen.

merci sueno <3

**Comment by ninoflorj** [comment]
Sehr geehrter Herr Sprudel,

Dies liegt daran, dass die Kosten für Übernachtung & Znacht gleich hoch sind, wie nur der Znacht.

Trotzdem danke für ihr nörgeln😉

Grüess,
Nino Florjancic v/o Sueno
